version: '3'

services:
  db:
    image: postgres:14
    volumes:
      - ./data:/var/lib/postgresql/data
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
  app:
    container_name: sayhellotobike
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - requirements=requirements.txt
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/sayhellotobike
    ports:
      - '8000:8000'
    depends_on:
      - db
