# Generated by Django 3.2.8 on 2023-05-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32, verbose_name='ユーザ名')),
                ('birth_day', models.DateField(verbose_name='生年月日')),
                ('age', models.PositiveSmallIntegerField(null=True, verbose_name='年齢')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
        ),
    ]
