# Generated by Django 3.2.8 on 2023-08-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayhellotobikeAPI', '0002_auto_20230815_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='birth_day',
        ),
    ]
