# Generated by Django 3.2.8 on 2023-11-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayhellotobikeAPI', '0005_userinfo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='image',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_day',
            field=models.DateField(verbose_name='生年月日'),
        ),
    ]
